name = "scarf-mini-app"
main = "src/index.ts"
compatibility_date = "2026-07-04"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "../dist"

[[d1_databases]]
binding = "DB"
database_name = "scarf-mini-app-db"
database_id = "d6b5b835-02ae-4b67-a507-5eae84aae0c3"

[vars]
BASE_URL = "https://scarf-mini-app.abdollahi003.workers.dev"
